insert into Instructors (name) values ('Donald F Ferguson');
insert into Instructors (name) values ('Luis Gravano');
insert into Instructors (name) values ('Alexandros Biliris');
insert into Instructors (name) values ('Baishakhi Ray');
insert into Instructors (name) values ('Stephen A Edwards');
insert into Instructors (name) values ('Jae W Lee');
insert into Instructors (name) values ('Gail E Kaiser');
insert into Instructors (name) values ('Changxi Zheng');
insert into Instructors (name) values ('Brian A Smith');
insert into Instructors (name) values ('Suman Jana');
insert into Instructors (name) values ('Michael S Sikorski');
insert into Instructors (name) values ('Rocco Servedio');